# Generated by Django 3.1.3 on 2023-01-13 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consumption_data', '0002_auto_20230113_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy_consumption',
            name='date_used',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
